nginx_vhosts:
  - listen: "80"
    server_name: "keybase.media.mit.edu"
    root: "/var/www/keybase.media.mit.edu"
    index: "index.php index.html index.htm"
    error_page: ""
    access_log: ""
    error_log: ""
    extra_parameters: |
        location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }
  - listen: "80"
    server_name: "hilda.geeklings.net"
    root: "/var/www/keybase.media.mit.edu"
    index: "index.php index.html index.htm"
    error_page: ""
    access_log: ""
    error_log: ""
    extra_parameters: |
        location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }
